'use strict';
const $ = (s, root = document) => root.querySelector(s);
const $$ = (s, root = document) => [...root.querySelectorAll(s)];
const esc = s => String(s ?? '').replace(/[&<>"']/g, c => ({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const uid = () => 'id-' + Math.random().toString(36).slice(2, 10);
const now = () => new Date().toLocaleTimeString([], {hour:'2-digit',minute:'2-digit'});
const STORAGE = 'sapi-workspace-prototype-v1';
const tabTypes = {computer:['▣','Computer'],overview:['◫','Overview'],artifacts:['▤','Artifacts'],github:['⑂','GitHub'],slack:['#','Slack'],connections:['◎','Connections'],document:['▧','Kickoff brief'],custom:['↗','Website']};
const seed = {
  agents:[
    {id:'jared',name:'Jared',role:'Chief of staff',color:'#d8e5f4',face:'◠‿◠',scope:'personal',status:'online',preview:'Your day, already sorted.',autonomy:'auto'},
    {id:'aaron',name:'Aaron',role:'Tech lead',color:'#f7d6d1',face:'•̀ᴗ•́',scope:'team',status:'busy',preview:'Getting Brightside pilot-ready.',autonomy:'auto'},
    {id:'designers',kind:'group',name:'Designers',role:'Creative studio · 3 Sapis',color:'#dbd0f7',face:'✿◠‿◠',scope:'team',status:'online',preview:'A fresh look for the kickoff.',autonomy:'auto'},
    {id:'slack',name:'SlackTwin',role:'Your communications twin',color:'#c9f3f1',face:'◕‿◕',scope:'personal',status:'online',preview:'Keeping everyone in the loop.',autonomy:'auto'},
    {id:'scout',name:'Scout',role:'Research & discovery',color:'#fdd997',face:'¬‿¬',scope:'team',status:'idle',preview:'Ready for the next rabbit hole.',autonomy:'auto'}
  ],
  selected:'aaron',scope:'all',panel:'chat',mode:'auto',panes:{sidebar:true,chat:true,workspace:true},
  tabs:[{id:'computer',type:'computer',title:'Computer'},{id:'overview',type:'overview',title:'Overview'},{id:'brief',type:'document',title:'Kickoff brief'}],activeTab:'computer',
  computer:{owner:'aaron',lastUsed:'aaron',paused:false,queue:['designers','slack'],completed:1},
  tasks:[
    {id:'pilot',agent:'aaron',title:'Get Brightside pilot-ready',description:'Verify Slack integration and SSO, share the launch update, and prepare the kickoff brief.',status:'In progress',progress:67},
    {id:'review',agent:'aaron',title:'Review the SSO pull request',description:'Check the authentication flow and leave a technical review in the demo repository.',status:'Queued',progress:0},
    {id:'sync',agent:'aaron',title:'Sync account context',description:'Gather the latest meeting notes and refresh the account summary.',status:'Done',progress:100},
    {id:'design',agent:'designers',title:'Polish the kickoff deck',description:'Bring the new visual identity into the Brightside introduction deck.',status:'Queued',progress:25},
    {id:'comms',agent:'slack',title:'Share the launch recap',description:'Post the pilot checklist and product updates to the team channel.',status:'Queued',progress:0},
    {id:'day',agent:'jared',title:'Prepare your morning briefing',description:'Summarize team progress, next steps, and calendar priorities.',status:'Done',progress:100},
    {id:'research',agent:'scout',title:'Research the next 5 accounts',description:'Collect public company context and identify product fit.',status:'Queued',progress:0}
  ],
  logs:[
    {agent:'aaron',time:'09:42',title:'Acquired team computer',detail:'Exclusive control granted. Designers and SlackTwin joined the queue.'},
    {agent:'aaron',time:'09:41',title:'Kickoff brief created',detail:'Meeting notes and account context brought together in a new artifact.'},
    {agent:'aaron',time:'09:40',title:'Product update shared',detail:'Simulated post to #brightside-shared completed.'},
    {agent:'aaron',time:'09:39',title:'Verified Slack + SSO release',detail:'Both features are available in the demo release.'},
    {agent:'jared',time:'09:35',title:'Morning briefing completed',detail:'All team updates collected.'}
  ],
  schedules:[{id:'daily',agent:'aaron',title:'Daily engineering pulse',frequency:'Every weekday at 09:00',prompt:'Summarize pull requests, blockers, and the next engineering priorities.',enabled:true,runs:12},{id:'pilot-check',agent:'aaron',title:'Check on Brightside',frequency:'Every 2 hours',prompt:'Check the pilot checklist and flag anything that needs attention.',enabled:true,runs:4}],
  messages:{aaron:[{role:'user',time:'09:38',text:'Where are we with Brightside Health? Let’s get them ready for the pilot.'},{role:'assistant',time:'09:39',text:'On it. Their last call flagged two must-haves: Slack integration and SSO. Both shipped last week, so I’m connecting the dots.',execution:true},{role:'assistant',time:'09:42',text:'Update shared in #brightside-shared. I also pulled the account context into a kickoff brief.\n\nNext up: a final pass on SSO, then I’ll hand the computer to Designers.',artifact:true}]},
  document:{title:'Brightside Health',subtitle:'Pilot kickoff brief',body:'The next chapter starts here.\n\nBrightside is ready to start a pilot now that Slack integration and single sign-on are available. This brief brings the latest account context and next steps into one place.\n\nPilot goals\n• Connect Brightside’s team through Slack.\n• Enable secure access with single sign-on.\n• Validate the core workflow with a small pilot group.\n\nWhat’s already done\n• Slack integration shipped and verified.\n• SSO release confirmed with engineering.\n• Product update shared in #brightside-shared.\n\nNext steps\n1. Aaron — complete the final SSO review.\n2. Designers — prepare the kickoff deck.\n3. Jared — coordinate a kickoff time with the team.',edited:false},
  connections:{Slack:true,GitHub:true,Drive:true,Calendar:true},posts:[],attachment:false
};
let state;
try { state = JSON.parse(localStorage.getItem(STORAGE)); } catch {}
if(!state || !Array.isArray(state.agents) || !state.computer || !state.document) state = structuredClone(seed);
state.panes = {sidebar:true,chat:true,workspace:true,...state.panes};
state.computer.lastUsed ??= state.computer.owner || null;
state.scope = ({personal:'sapis',team:'groups'})[state.scope] || state.scope;
for(const a of state.agents) a.kind ??= a.id==='designers'?'group':'sapi';
state.drafts ??= {};
let search = '', toastTimer, dragId, pending = new Set();
const agent = id => state.agents.find(a=>a.id===id) || state.agents[0];
const selected = () => agent(state.selected);
const isGroup = a => a.kind==='group' || a.id==='designers';
const groupAvatarCache = new Map();
function groupAvatar(a){
  const key=JSON.stringify([a.id,a.name,a.face,a.color,a.groupAvatar]);
  if(!groupAvatarCache.has(key)){
    const safeColor=/^#[a-f0-9]{6}$/i.test(a.color)?a.color:'#dbd0f7';
    const group=a.groupAvatar || {id:a.id,name:a.name,lead:{id:a.id+'-lead',expression:a.face,colour:safeColor},peers:[{id:a.id+'-peer-1',expression:'◕‿◕',colour:'#c9f3f1'},{id:a.id+'-peer-2',expression:'◠‿◠',colour:'#f7d6d1'}],groups:[]};
    const svg=SapiGroupAvatar.render(group,{tight:true});
    groupAvatarCache.set(key,'data:image/svg+xml;charset=utf-8,'+encodeURIComponent(svg));
  }
  return groupAvatarCache.get(key);
}
const avatar = (a, size='', presence=false) => `<span class="avatar ${size} ${isGroup(a)?'group-avatar':''}" style="--avatar-color:${/^#[a-f0-9]{6}$/i.test(a.color)?a.color:'#fdd997'}" aria-hidden="true">${isGroup(a)?`<img src="${esc(groupAvatar(a))}" alt="">`:`(${esc(a.face)})`}${presence?`<i class="presence ${a.status==='busy'?'busy':a.status==='idle'?'idle':''}"></i>`:''}</span>`;
function mention(id){
  const a=state.agents.find(a=>a.id===id);
  return a?`<button type="button" class="entity-mention" data-mention="${esc(a.id)}" aria-label="Open chat with ${esc(a.name)}">@${esc(a.name)}</button>`:esc(id==='you'?'You':id);
}
function formatText(value){
  const text=String(value??'');
  const names=state.agents.map(a=>a.name).filter(Boolean).sort((a,b)=>b.length-a.length).map(name=>name.replace(/[.*+?^${}()|[\]\\]/g,'\\$&'));
  if(!names.length)return esc(text);
  const pattern=new RegExp(`(?<![\\p{L}\\p{N}_@.-])@?(?:${names.join('|')})(?![\\p{L}\\p{N}_@-])`,'giu');
  let result='',cursor=0;
  for(const match of text.matchAll(pattern)){
    const name=match[0].replace(/^@/,'').toLowerCase();
    const a=state.agents.find(a=>a.name.toLowerCase()===name);
    result+=esc(text.slice(cursor,match.index))+(a?mention(a.id):esc(match[0]));cursor=match.index+match[0].length;
  }
  return result+esc(text.slice(cursor));
}
function openChat(id){
  const a=state.agents.find(a=>a.id===id);if(!a)return;
  state.drafts ??= {};state.drafts[state.selected]=$('#message-input').value;
  state.selected=id;state.panel='chat';state.panes.chat=true;
  if(state.scope!=='all')state.scope=isGroup(a)?'groups':'sapis';
  search='';$('#agent-search').value='';$('#message-input').value=state.drafts[id]||'';
  closeModal();render();$('#conversation-body').scrollTop=$('#conversation-body').scrollHeight;
}
function save(){try{localStorage.setItem(STORAGE,JSON.stringify(state));$('#workspace-footer-status').textContent='Saved locally';}catch{$('#workspace-footer-status').textContent='Saved for this session';}}
function toast(message){$('#toast').textContent=message;$('#toast').classList.add('visible');clearTimeout(toastTimer);toastTimer=setTimeout(()=>$('#toast').classList.remove('visible'),3200);}
function log(agentId,title,detail){state.logs.unshift({agent:agentId,time:now(),title,detail});state.logs=state.logs.slice(0,100);}
function modal(title,content,eyebrow='SAPI WORKSPACE'){$('#modal-eyebrow').textContent=eyebrow;$('#modal-content').innerHTML=`<h2 id="modal-title">${esc(title)}</h2>${content}`;if(!$('#modal').open)$('#modal').showModal();}
function closeModal(){$('#modal').close();}
function render(){renderPanes();renderSidebar();renderAgentHeader();renderConversation();renderTabs();renderWorkspace();renderGlobal();save();}
function renderPanes(){
  state.panes ??= {sidebar:true,chat:true,workspace:true};
  const names={sidebar:'chat list',chat:'chat',workspace:'workspace'};
  const ids={sidebar:'#chat-list-panel',chat:'#chat-panel',workspace:'#workspace-panel'};
  for(const pane of Object.keys(ids)){
    $(ids[pane]).hidden=!state.panes[pane];
    const button=$(`[data-toggle-pane="${pane}"]`);
    button.setAttribute('aria-pressed',String(state.panes[pane]));
    button.setAttribute('aria-expanded',String(state.panes[pane]));
    const label=`${state.panes[pane]?'Hide':'Show'} ${names[pane]}`;
    button.setAttribute('aria-label',label);button.title=label;
  }
  const p=state.panes;
  const count=Object.values(p).filter(Boolean).length;
  $('.main-grid').dataset.visiblePanes=count;
  $('.main-grid').style.gridTemplateColumns=[p.sidebar?(count===1?'minmax(0,1fr)':'clamp(205px,18vw,250px)'):'0px',p.chat?'minmax(300px,1fr)':'0px',p.workspace?'minmax(350px,1.2fr)':'0px'].join(' ');
}
function renderGlobal(){
  $('#autonomy-label').textContent={auto:'Autonomous',assist:'Assisted',paused:'Paused'}[state.mode];
  const c=state.computer;
  const who=id=>id==='you'?'You':mention(id);
  $('#resource-owner').innerHTML=c.owner?`${c.paused||state.mode==='paused'?'Paused':'In use'} · ${who(c.owner)}`:c.lastUsed?`Last used by ${who(c.lastUsed)}`:'Available';
  $('#resource-status').classList.toggle('idle',!c.owner);
  $('#resource-status').classList.toggle('paused',c.paused||state.mode==='paused');
  $('#task-count').textContent=state.tasks.filter(t=>t.agent===state.selected&&t.status!=='Done').length;
}
function renderSidebar(){
  $('#agent-count').textContent=String(state.agents.length).padStart(2,'0');
  $$('[data-scope]').forEach(b=>{b.classList.toggle('active',b.dataset.scope===state.scope);b.setAttribute('aria-pressed',b.dataset.scope===state.scope);});
  const list=state.agents.filter(a=>(state.scope==='all'||(state.scope==='groups'?isGroup(a):!isGroup(a)))&&`${a.name} ${a.role}`.toLowerCase().includes(search.toLowerCase()));
  $('#agent-list').innerHTML=list.length?list.map(a=>`<button class="agent-row ${a.id===state.selected?'active':''}" data-agent="${esc(a.id)}" aria-pressed="${a.id===state.selected}">${avatar(a,'',true)}<span class="agent-row-copy"><span class="agent-row-name">${esc(a.name)}<small>${a.id==='aaron'?'09:42':a.id==='designers'?'09:38':'09:35'}</small></span><p>${esc(a.preview)}</p></span>${a.id===state.selected?'':'<span class="unread-dot"></span>'}</button>`).join(''):'<div class="empty">No Sapis found.</div>';
}
function renderAgentHeader(){const a=selected();$('#agent-heading').innerHTML=`${avatar(a,'large')}<div><h2>${esc(a.name)} <span class="muted" style="font-weight:400">/ ${esc(a.role.split(' ·')[0])}</span></h2><p><span class="status-dot"></span> ${state.mode==='paused'?'Paused':a.autonomy==='auto'?'Autonomous':'Assisted'}</p></div><button class="icon-button" data-action="agent-settings" aria-label="Agent settings">···</button>`;$('#message-input').placeholder=`Message ${a.name}…`;$$('[data-panel]').forEach(b=>{b.classList.toggle('active',b.dataset.panel===state.panel);b.setAttribute('aria-pressed',b.dataset.panel===state.panel);});$('.composer-hint span').textContent=state.mode==='paused'?'Ⅱ Team paused':a.autonomy==='auto'?'Autonomous':'Assisted';}
function getMessages(id){if(!state.messages[id]){const a=agent(id);state.messages[id]=[{role:'assistant',time:'09:35',text:({jared:'Good morning, Alex. The team is making progress on Brightside. Aaron has the technical work, Designers are up next on the shared computer, and I’m keeping the bigger picture together.\n\nWhat would you like to move forward today?',designers:'We’ve got the kickoff deck on our list. We’re next in line for the shared computer—once Aaron wraps up, we’ll take it from there.',slack:'I’m keeping an eye on team conversations and collecting the updates that matter. The Brightside recap is ready for a final pass.',scout:'Ready to explore. Give me an account, a question, or a hunch, and I’ll turn it into something useful.'})[id]||`Hi, I’m ${a.name}. Give me a task and I’ll get started.`}];}return state.messages[id];}
function executionCard(){return `<div class="execution-card"><div class="execution-title">Actions <span>3 / 3</span></div><div class="execution-line"><span class="check">✓</span> Read meeting notes & account context <time>2s</time></div><div class="execution-line"><span class="check">✓</span> Verify Slack + SSO release <time>4s</time></div><div class="execution-line"><span class="check">✓</span> Share update with Brightside <time>3s</time></div></div>`;}
function renderConversation(){const host=$('#conversation-body');$('#composer-area').hidden=state.panel!=='chat';renderAgentHeader();renderGlobal();
  if(state.panel==='chat'){const a=selected();const messages=getMessages(a.id);host.innerHTML=`<div class="day-divider">TODAY</div>`+messages.map(m=>`<div class="message ${m.role==='user'?'user':''}"><div class="message-meta">${m.role==='assistant'?avatar(a,'mini'):'<span>↗</span>'}<strong>${m.role==='user'?'You':mention(a.id)}</strong><time>${esc(m.time)}</time></div><div class="message-bubble">${m.text.split('\n\n').map(p=>`<p>${formatText(p).replace(/\n/g,'<br>')}</p>`).join('')}${m.execution?executionCard():''}${m.artifact?'<button class="artifact-link" data-action="open-brief"><span class="file-icon">▤</span><span><strong>Brightside · Kickoff brief</strong><small>DOCUMENT · JUST UPDATED</small></span><span>↗</span></button>':''}</div>${m.artifact?'<div class="message-foot">✓ Context saved to the workspace</div>':''}</div>`).join('')+(pending.has(a.id)?`<div class="typing" role="status">${esc(a.name)} is working through it ···</div>`:'')+`<div class="suggestions"><button data-suggest="Show me the next steps">What’s next? ↗</button><button data-suggest="Prepare a progress report">Make a progress report ↗</button></div>`;renderAttachment();}
  if(state.panel==='tasks')host.innerHTML=`<div class="list-heading"><h3>${esc(selected().name)}’s tasks</h3><button class="button" data-action="new-task">＋ Task</button></div>`+state.tasks.filter(t=>t.agent===state.selected).map(taskCard).join('')+(state.tasks.some(t=>t.agent===state.selected)?'':'<div class="empty">A clean slate. Add the first task.</div>');
  if(state.panel==='log')host.innerHTML=`<div class="list-heading"><h3>Activity log</h3><span class="tag">SIMULATED</span></div>`+state.logs.filter(l=>l.agent===state.selected).map(l=>`<div class="log-row"><time>${esc(l.time)}</time><strong>${esc(l.title)}</strong><p>${formatText(l.detail)}</p></div>`).join('')+(state.logs.some(l=>l.agent===state.selected)?'':'<div class="empty">New activity will appear here.</div>');
  if(state.panel==='cron')host.innerHTML=`<div class="list-heading"><h3>Schedules</h3><button class="button" data-action="new-schedule">＋ Schedule</button></div><p class="form-hint" style="margin-bottom:17px">Demo schedules. Use “Run now” to preview an execution.</p>`+state.schedules.filter(s=>s.agent===state.selected).map(s=>`<div class="schedule-card"><div class="task-card-top"><h3>${esc(s.title)}</h3><button class="switch ${s.enabled?'':'off'}" role="switch" aria-checked="${s.enabled}" aria-label="Enable ${esc(s.title)}" data-toggle-schedule="${s.id}"></button></div><p>${esc(s.prompt)}</p><span class="schedule-meta">↻ ${esc(s.frequency)}</span><div class="actions"><small class="muted">${s.runs} runs · ${s.enabled?'Active':'Paused'}</small><button class="button soft" data-run-schedule="${s.id}">▷ Run now</button><button class="icon-button" data-edit-schedule="${s.id}" aria-label="Edit ${esc(s.title)}">···</button></div></div>`).join('')+(state.schedules.some(s=>s.agent===state.selected)?'':'<div class="empty">Set up a recurring task for this Sapi.</div>');
}
function taskCard(t){const a=agent(t.agent);return `<article class="task-card"><button class="task-open" data-task="${esc(t.id)}"><div class="task-card-top"><span class="tag ${t.status==='Queued'?'gray':t.status==='In progress'?'amber':''}">${t.status==='Done'?'✓ ':t.status==='In progress'?'◌ ':''}${esc(t.status)}</span><span class="muted">↗</span></div><h3>${esc(t.title)}</h3><p>${esc(t.description)}</p>${t.status==='In progress'?`<div class="progress-track" role="progressbar" aria-label="Task progress" aria-valuenow="${t.progress}" aria-valuemin="0" aria-valuemax="100"><span style="width:${t.progress}%"></span></div>`:''}</button><div class="task-card-bottom">${avatar(a,'mini')} ${mention(a.id)}<span class="tag gray">${t.status==='Done'?'Completed':'Brightside pilot'}</span></div></article>`;}
function renderTabs(){const host=$('#browser-tabs');host.innerHTML=state.tabs.map(t=>`<div class="workspace-tab ${t.id===state.activeTab?'active':''}" draggable="true" data-drag-tab="${esc(t.id)}"><button class="tab-select" data-tab="${esc(t.id)}" aria-pressed="${t.id===state.activeTab}"><span class="tab-icon">${tabTypes[t.type]?.[0]||'↗'}</span>${esc(t.title)}</button><button class="tab-close" data-close-tab="${esc(t.id)}" aria-label="Close ${esc(t.title)}">×</button></div>`).join('');
  $$('[data-drag-tab]').forEach(el=>{el.addEventListener('dragstart',e=>{dragId=el.dataset.dragTab;e.dataTransfer.setData('text/plain',dragId);e.dataTransfer.effectAllowed='move';});el.addEventListener('dragover',e=>e.preventDefault());el.addEventListener('drop',e=>{e.preventDefault();const target=el.dataset.dragTab;const from=state.tabs.findIndex(t=>t.id===dragId),to=state.tabs.findIndex(t=>t.id===target);if(from<0||to<0)return;state.tabs.splice(to,0,state.tabs.splice(from,1)[0]);renderTabs();save();});el.addEventListener('dblclick',e=>{if(!e.target.closest('[data-close-tab]'))tabSettings(el.dataset.dragTab);});});
}
function openTab(type,title,extra={}){let t=state.tabs.find(t=>t.type===type&&type!=='custom');if(!t){t={id:uid(),type,title:title||tabTypes[type][1],...extra};state.tabs.push(t);}state.activeTab=t.id;state.panes.workspace=true;renderPanes();renderTabs();renderWorkspace();save();}
function renderWorkspace(){const t=state.tabs.find(t=>t.id===state.activeTab);const host=$('#workspace-content');if(!t){host.innerHTML='<div class="empty"><span style="font-size:48px">✳</span><h2 style="margin:15px 0">No tabs open</h2><button class="button primary" data-action="new-tab" style="margin-top:20px">＋ Add a tab</button></div>';return;}
  const views={computer:computerView,overview:overviewView,document:documentView,artifacts:artifactsView,github:githubView,slack:slackView,connections:connectionsView,custom:()=>customView(t)};host.innerHTML=(views[t.type]||views.custom)();
}
function computerView(){const c=state.computer,a=c.owner&&c.owner!=='you'?agent(c.owner):null,locked=!!c.owner,paused=c.paused||state.mode==='paused';return `<div class="section-title"><div><p class="eyebrow">COMPUTER SESSION</p><h2>Shared computer<span style="color:#a4ae95"> ↗</span></h2></div><div class="actions"><span class="tag ${paused?'amber':''}"><span class="status-dot"></span>${paused?'PAUSED':'DEMO SESSION'}</span></div></div>
    <div class="lock-banner ${paused?'computer-paused':''}"><span class="lock-symbol">${locked?'▣':'◇'}</span><div><strong>${paused?'Session paused':c.owner==='you'?'You have the controls':a?`${mention(a.id)} has the controls`:'The computer is available'}</strong><p>${paused?'The current lock is held until you resume or hand off.':c.owner==='you'?'Agents are waiting while you use the computer.':a?'Other Sapis can watch. Only the owner can act.':'Assign an agent below to start a session.'}</p></div><span class="tag">${locked?'LOCKED':'FREE'}</span></div>
    <div class="computer-window ${paused?'screen-paused':''}"><div class="computer-toolbar"><div class="traffic"><i></i><i></i><i></i></div><span class="address">▣ &nbsp; ${a?.id==='designers'?'slides.demo / brightside-kickoff':a?.id==='scout'?'research.demo / accounts':'slack.demo / brightside-shared'}</span><span class="tag">↗</span></div><div class="mock-screen"><div class="mock-rail"><span class="slack-symbol">${a?.id==='designers'?'▤':'#'}</span><span>⌂</span><span>☷</span><span>♧</span><span>＋</span></div><div class="mock-channel"><div class="channel-header">${a?.id==='designers'?'Brightside · Kickoff deck':'# brightside-shared'} <span>☆ &nbsp; 12 members</span></div><div class="channel-post"><span class="user-avatar">AP</span><div><strong>Alex Parker</strong><time>9:38 AM</time><p>Excited to get the pilot rolling. Let’s bring everything together here.</p></div></div><div class="channel-post">${avatar(a||agent('aaron'),'mini')}<div><strong>${mention(a?.id||'aaron')} <span class="tag gray" style="font-size:7px;padding:1px 4px">SAPI</span></strong><time>9:42 AM</time><p>${a?.id==='designers'?'Working on the kickoff deck. A fresh start for a new chapter.':'A quick update from our side ✦'}</p></div></div><div class="posted-card"><b>${a?.id==='designers'?'Meet your new way of working.':'Both boxes, checked.'}</b>${a?.id==='designers'?'Brightside Health × Sapi<br>A pilot built around your team.':'✓ &nbsp; Slack integration is live.<br>✓ &nbsp; Single sign-on is ready.<br>We’re all set to move into the pilot.'}</div></div>${a&&!paused?`<div class="screen-cursor">➤ <span>${mention(a.id)}</span></div>`:''}</div><div class="computer-caption"><span>● ${paused?'Session on hold':locked?'Exclusive input · Shared visibility':'No active controller'}</span><span>Demo computer &nbsp; · &nbsp; 1440 × 900</span></div></div>
    <div class="computer-controls"><div class="actions"><button class="button primary" data-action="take-control">${c.owner==='you'?'↗ Release control':'↗ Take control'}</button><button class="button" data-action="pause-computer">${paused?'▷ Resume':'Ⅱ Pause'}</button><button class="button" data-action="handoff" ${!c.queue.length?'disabled':''}>Hand off →</button></div><span>${c.completed} handoffs today</span></div>
    <div class="subheading"><h3>Next at the controls</h3><button class="text-button" data-action="join-queue" style="font-size:10px">＋ Add to queue</button></div><div class="queue">${c.queue.map((id,i)=>{const q=agent(id);return `<div class="queue-row"><span class="queue-position">0${i+1}</span>${avatar(q)}<div class="queue-row-copy"><strong>${mention(q.id)}</strong><p>${esc(q.id==='designers'?'Polish the kickoff deck':q.id==='slack'?'Share the launch recap':q.role)}</p></div><span class="tag ${i===0?'amber':'gray'}">${i===0?'UP NEXT':'QUEUED'}</span><button class="icon-button" data-remove-queue="${esc(id)}" aria-label="Remove ${esc(q.name)} from queue">×</button></div>`;}).join('')||'<div class="empty">No one is waiting. Room to do your thing.</div>'}</div><p class="resource-help">Sapis pass the lock as they finish. You can step in anytime.</p>`;}
function overviewView(){const done=state.tasks.filter(t=>t.status==='Done').length;return `<div class="section-title"><div><p class="eyebrow">TODAY</p><h2>Overview</h2></div><button class="button" data-action="new-task">＋ Task</button></div><div class="metrics"><div class="metric"><strong>${state.agents.length.toString().padStart(2,'0')}</strong><p>Agents</p></div><div class="metric"><strong>${done.toString().padStart(2,'0')}</strong><p>Tasks completed</p></div><div class="metric"><strong>${state.tasks.filter(t=>t.status==='In progress').length.toString().padStart(2,'0')}</strong><p>Running</p></div></div><div class="subheading"><h3>Open tasks</h3><span>${state.tasks.filter(t=>t.status!=='Done').length} open tasks</span></div>${state.tasks.filter(t=>t.status!=='Done').map(taskCard).join('')}<div class="subheading" style="margin-top:24px"><h3>Recent artifacts</h3><button class="text-button" data-action="open-artifacts" style="font-size:10px">All artifacts ↗</button></div>${artifactButton()}`;}
function artifactButton(){return `<div class="artifact-item"><span class="file-icon">▤</span><div><button class="artifact-open" data-action="open-brief"><strong>Brightside · Kickoff brief</strong></button><p>By ${mention('aaron')} · Updated today</p></div><button class="icon-button" data-action="open-brief" aria-label="Open kickoff brief">↗</button></div>`;}
function documentView(){return `<div class="section-title"><div><p class="eyebrow">ARTIFACT / DOCUMENT</p><h2>Document</h2></div><div class="actions"><button class="button" data-action="edit-document">Edit</button><button class="button primary" data-action="download-document">↓ Export</button></div></div><article class="doc-page"><div class="doc-icon">✳</div><h2>${esc(state.document.title)}<br><span style="color:#96a284">${esc(state.document.subtitle)}</span></h2><div class="doc-meta">${avatar(agent('aaron'),'mini')} ${mention('aaron')} · Tech lead <span style="margin-left:auto">${state.document.edited?'Edited locally':'Updated today'}</span></div>${state.document.body.split('\n\n').map((p,i)=>i===0?`<h3>${esc(p)}</h3>`:`<p style="margin-bottom:18px">${formatText(p).replace(/\n/g,'<br>')}</p>`).join('')}<div class="doc-callout">✦ Source context: account notes, product releases, and the team conversation. All content in this playground is sample data.</div></article>`;}
function artifactsView(){return `<div class="section-title"><div><p class="eyebrow">MADE BY YOUR TEAM</p><h2>Artifacts</h2><p></p></div></div><div class="artifact-list">${artifactButton()}<button class="artifact-item" data-action="open-report"><span class="file-icon" style="background:#e9e1f4">◫</span><span><strong>Team progress report</strong><p>All Sapis · Live demo summary</p></span><span>↗</span></button></div>`;}
function githubView(){return `<div class="section-title"><div><p class="eyebrow">CONNECTED APP / DEMO</p><h2>GitHub</h2></div><span class="tag">${state.connections.GitHub?'CONNECTED':'DISCONNECTED'}</span></div><div class="repo-title">⑂ &nbsp; sapi / brightside-pilot</div>${[{n:142,title:'Add single sign-on for pilot accounts',tag:'Review',desc:'Aaron · 4 files changed · +128 −24'},{n:139,title:'Connect workspace events to Slack',tag:'Merged',desc:'Aaron · merged yesterday'},{n:136,title:'Add pilot onboarding checklist',tag:'Merged',desc:'Jared · merged 2 days ago'}].map(x=>`<button class="repo-item" data-pr="${x.n}"><span style="color:#829567">⑂</span><div><strong>${x.title}</strong><p>#${x.n} · ${x.desc}</p></div><span class="tag ${x.tag==='Review'?'amber':'lilac'}">${x.tag}</span></button>`).join('')}<p class="resource-help">Sample repository activity. Selecting a pull request opens its demo details.</p>`;}
function slackView(){return `<div class="section-title"><div><p class="eyebrow">CONNECTED APP / DEMO</p><h2># brightside-shared</h2></div><span class="tag">${state.connections.Slack?'CONNECTED':'DISCONNECTED'}</span></div><div class="doc-page"><div class="message-meta">${avatar(agent('aaron'),'mini')}<strong>${mention('aaron')}</strong><time>09:40</time></div><p>Both Slack integration and SSO are ready. We’re all set to move into the pilot. I’ve added the kickoff brief to the workspace.</p>${state.posts.map(p=>`<div style="border-top:1px solid #dbe0cf;margin-top:20px;padding-top:15px"><div class="message-meta"><strong>${formatText(p.author)}</strong><time>${esc(p.time)}</time></div><p>${formatText(p.text)}</p></div>`).join('')}<form id="slack-form" class="form-stack" style="margin-top:22px"><label>Post to the demo channel<input name="post" required placeholder="Share an update…" maxlength="1000"></label><button class="button primary" type="submit">Post update ↗</button></form></div>`;}
function connectionsView(){return `<div class="section-title"><div><p class="eyebrow">CONNECTED APPS</p><h2>Your connections</h2><p>Demo connections your Sapis can work with.</p></div></div><div class="connection-grid">${Object.entries(state.connections).map(([name,on])=>`<button class="connection-card" data-connection="${name}"><span class="connection-logo">${{Slack:'#',GitHub:'⑂',Drive:'△',Calendar:'▦'}[name]}</span><strong>${name}</strong><p>${{Slack:'Conversations & updates',GitHub:'Code & pull requests',Drive:'Documents & artifacts',Calendar:'Schedules & meetings'}[name]}</p><span class="tag ${on?'':'gray'}">${on?'● Connected':'○ Disconnected'}</span></button>`).join('')}</div><p class="resource-help">Toggle sample connections to explore setup states. No external accounts are connected.</p>`;}
function customView(t){return `<div class="section-title"><div><p class="eyebrow">YOUR WORKSPACE / BOOKMARK</p><h2>${esc(t.title)}</h2></div><button class="button" data-edit-tab="${esc(t.id)}">Edit tab</button></div><div class="overview-hero"><h2>Website bookmark</h2><p>This tab saves a website alongside your agents and artifacts.</p></div><div class="custom-link"><span>↗</span><a href="${esc(safeUrl(t.url)||'#')}" target="_blank" rel="noopener noreferrer">Open ${esc(t.title)} in a new browser tab</a></div><p class="resource-help">${esc(t.url)}<br>Website tabs are bookmarks in this HTML prototype.</p>`;}
function safeUrl(value){try{const u=new URL(value);return /^https?:$/.test(u.protocol)?u.href:null;}catch{return null;}}
function addTabDialog(){modal('Add tab',`<p>Drag tabs to reorder. Double-click to rename.</p><div class="tab-type-grid">${['computer','overview','artifacts','github','slack','connections'].map(type=>`<button class="tab-type" data-new-tab-type="${type}"><span>${tabTypes[type][0]}</span>${tabTypes[type][1]}</button>`).join('')}</div><form id="custom-tab-form" class="form-stack"><div class="form-row"><label>Tab name<input name="title" placeholder="My tool" required maxlength="32"></label><label>Website URL<input name="url" type="url" placeholder="https://…" required></label></div><button type="submit" class="button primary">＋ Add website tab</button></form>`);}
function tabSettings(id){const t=state.tabs.find(t=>t.id===id);if(!t)return;modal('Tab settings',`<form class="form-stack" id="tab-settings-form" data-id="${esc(id)}"><label>Tab name<input name="title" value="${esc(t.title)}" maxlength="32" required></label>${t.type==='custom'?`<label>Website URL<input name="url" type="url" value="${esc(t.url)}" required></label>`:''}<button class="button primary" type="submit">Save tab</button></form><div class="modal-actions"><button class="button" data-move-tab="left" data-id="${esc(id)}">← Move left</button><button class="button" data-move-tab="right" data-id="${esc(id)}">Move right →</button><button class="button danger" data-close-tab="${esc(id)}">Close tab</button></div>`);}
function autonomyDialog(){modal('Autonomy',`<p>Sapis work autonomously by default. Shared computer access always belongs to one controller at a time.</p>${[['auto','✦','Autonomous','Agents complete demo tasks and pass the computer lock on their own.'],['assist','◇','Assisted','Agents prepare work. You choose when each demo task runs.'],['paused','Ⅱ','Pause the team','Stop new agent actions. Keep your workspace and computer lock.']].map(([mode,icon,title,desc])=>`<button class="auto-choice ${state.mode===mode?'selected':''}" data-mode="${mode}"><span>${icon}</span><span><strong>${title}</strong><small>${desc}</small></span></button>`).join('')}<p class="form-hint" style="margin-top:18px">You can also adjust autonomy for each Sapi in its settings.</p>`);}
function agentSettings(){const a=selected();modal(`${a.name} settings`,`<div class="agent-profile">${avatar(a)}<div><strong>${esc(a.role)}</strong><p class="form-hint" style="margin-top:5px">${isGroup(a)?'Group · Voronoi avatar':'Individual Sapi'} · ${a.status==='idle'?'Standing by':'Available'}</p></div></div><form id="agent-settings-form" class="form-stack"><label>Name<input name="name" value="${esc(a.name)}" required maxlength="24"></label><label>Role<input name="role" value="${esc(a.role)}" required maxlength="60"></label><label>Autonomy<select name="autonomy"><option value="auto" ${a.autonomy==='auto'?'selected':''}>Autonomous — execute and report</option><option value="assist" ${a.autonomy==='assist'?'selected':''}>Assisted — prepare, then wait</option></select></label><button class="button primary" type="submit">Save Sapi</button></form>`,`SAPI / ${a.name.toUpperCase()}`);}
function addAgent(){modal('Add agent',`<form id="add-agent-form" class="form-stack"><div class="form-row"><label>Name<input name="name" required placeholder="e.g. Nova" maxlength="24"></label><label>Role<input name="role" required placeholder="e.g. Product strategist" maxlength="60"></label></div><div class="form-row"><label>Type<select name="kind"><option value="sapi">Sapi</option><option value="group">Group</option></select></label><label>Personality<select name="face"><option value="◕‿◕">(◕‿◕) Curious</option><option value="◠‿◠">(◠‿◠) Calm</option><option value="•̀ᴗ•́">(•̀ᴗ•́) Focused</option><option value="≧▽≦">(≧▽≦) Delighted</option></select></label></div><label>Avatar color<select name="color"><option value="#fdd997">Golden haze</option><option value="#f7d6d1">Rosewater</option><option value="#c9f3f1">Ice aqua</option><option value="#dbd0f7">Lavender</option><option value="#d8e5f4">Pale sky blue</option></select></label><p class="form-hint">Starts autonomous. You can adjust this anytime.</p><button type="submit" class="button primary">＋ Add agent</button></form>`);}
function newTask(){modal('New task',`<form id="new-task-form" class="form-stack"><label>Task<input name="title" required placeholder="What needs to get done?" maxlength="100"></label><label>Context<textarea name="description" placeholder="The details that will help your Sapi…" style="min-height:95px"></textarea></label><label>Assign to<select name="agent">${state.agents.map(a=>`<option value="${a.id}" ${a.id===state.selected?'selected':''}>${esc(a.name)} — ${esc(a.role)}</option>`).join('')}</select></label><button type="submit" class="button primary">Create task ↗</button></form>`);}
function taskDetails(id){const t=state.tasks.find(t=>t.id===id);if(!t)return;modal(t.title,`<p>${esc(t.description)}</p><div class="settings-row">${avatar(agent(t.agent),'mini')}<span>${mention(t.agent)}</span><span class="tag ${t.status==='In progress'?'amber':''}">${esc(t.status)}</span></div><p class="form-hint" style="margin-top:15px">Run the demo to simulate execution, generate a progress update, and record the result in the agent log.</p><div class="modal-actions"><button class="button" data-task-status="Queued" data-id="${t.id}">Queue</button><button class="button" data-task-status="Done" data-id="${t.id}">Mark done</button><button class="button primary" data-run-task="${t.id}" ${t.status==='Done'?'disabled':''}>▷ Run demo</button></div>`);}
function scheduleDialog(id){const s=state.schedules.find(x=>x.id===id);modal(s?'Edit schedule':'New schedule',`<form id="schedule-form" data-id="${s?.id||''}" class="form-stack"><label>Name<input name="title" value="${esc(s?.title||'')}" placeholder="e.g. Morning team briefing" required maxlength="80"></label><label>Repeat<select name="frequency">${['Every weekday at 09:00','Every day at 18:00','Every 2 hours','Every Monday at 10:00'].map(f=>`<option ${s?.frequency===f?'selected':''}>${f}</option>`).join('')}</select></label><label>What should ${esc(selected().name)} do?<textarea name="prompt" required placeholder="Summarize team progress and next steps…" style="min-height:100px">${esc(s?.prompt||'')}</textarea></label><button type="submit" class="button primary">${s?'Save changes':'Create schedule'}</button></form>${s?`<div class="modal-actions"><button class="button danger" data-delete-schedule="${s.id}">Delete schedule</button></div>`:''}`);}
function joinQueue(){const available=state.agents.filter(a=>a.id!==state.computer.owner&&!state.computer.queue.includes(a.id));modal('Computer queue',`<p>One Sapi at the controls. Everyone else has a place in line.</p>${available.map(a=>`<button class="auto-choice" data-queue-agent="${a.id}">${avatar(a)}<span><strong>${esc(a.name)}</strong><small>${esc(a.role)}</small></span><span style="margin-left:auto">＋</span></button>`).join('')||'<div class="empty">The whole team is already in line.</div>'}`);}
function handoff(auto=false){const c=state.computer;if(!c.queue.length){if(auto&&c.owner){c.lastUsed=c.owner;c.owner=null;render();}return false;}const old=c.owner;c.lastUsed=old||c.lastUsed;c.owner=c.queue.shift();c.paused=false;c.completed++;agent(c.owner).status='busy';if(old&&old!=='you')agent(old).status='online';log(c.owner,'Acquired team computer',`${auto?'Automatic handoff':'Control handed off'} from ${old==='you'?'you':old?agent(old).name:'the available pool'}. Exclusive lock granted.`);if(old&&old!=='you')log(old,'Released team computer',`Lock passed to ${agent(c.owner).name}.`);render();toast(`${agent(c.owner).name} now has the computer lock.`);return true;}
function canRun(agentId){if(state.mode==='paused'){toast('The team is paused. Resume it from the autonomy menu.');return false;}if(pending.has(agentId)){toast(`${agent(agentId).name} is already working on a demo task.`);return false;}return true;}
function runTask(id){const t=state.tasks.find(t=>t.id===id);if(!t||!canRun(t.agent))return;closeModal();t.status='In progress';t.progress=35;pending.add(t.agent);log(t.agent,'Task started',t.title);render();toast(`${agent(t.agent).name} is running the demo…`);setTimeout(()=>{pending.delete(t.agent);if(state.mode==='paused'){t.status='Queued';t.progress=0;log(t.agent,'Task paused',`${t.title} returned to the queue.`);render();return;}t.status='Done';t.progress=100;log(t.agent,'Task completed',`${t.title} · simulated execution.`);getMessages(t.agent).push({role:'assistant',time:now(),text:`Done: ${t.title}. I’ve recorded the result in my activity log and updated the task board.`,artifact:t.id==='pilot'});if(state.computer.owner===t.agent&&!state.computer.paused)handoff(true);else render();toast(`${t.title} — complete.`);},1600);}
function sendChat(value){const text=value.trim();if(!text)return;const id=state.selected;getMessages(id).push({role:'user',time:now(),text:text+(state.attachment?'\n\nAttached: Meeting notes.txt':'')});state.attachment=false;$('#message-input').value='';renderConversation();save();$('#conversation-body').scrollTop=$('#conversation-body').scrollHeight;
  if(state.mode==='paused'){getMessages(id).push({role:'assistant',time:now(),text:'I have your message. The team is paused, so I’ll wait here. Resume the team and send me the task when you’re ready.'});renderConversation();save();return;}
  if(pending.has(id)){toast('Message saved. This Sapi is finishing its current demo action.');return;}
  pending.add(id);renderConversation();$('#conversation-body').scrollTop=$('#conversation-body').scrollHeight;
  setTimeout(()=>{pending.delete(id);let reply,artifact=false;
    if(state.mode==='paused')reply='The team paused before I finished. Your message is saved; send it again when we’re ready to continue.';
    else if(/next|status|update|progress|report/i.test(text)){const tasks=state.tasks.filter(t=>t.agent===id&&t.status!=='Done');reply=`Here’s where things stand: ${state.tasks.filter(t=>t.agent===id&&t.status==='Done').length} task(s) complete, ${tasks.length} still in motion.\n\n${tasks.length?tasks.map((t,i)=>`${i+1}. ${t.title} — ${t.status.toLowerCase()}.`).join('\n'):'My plate is clear. Ready for the next thing.'}`;if(/report/i.test(text)){artifact=true;openTab('overview');}log(id,'Progress reviewed','Summarized task board and shared next steps.');}
    else if(/computer|control|lock/i.test(text)){if(state.computer.owner===id)reply='I already hold the computer lock. The rest of the team can observe, and I’ll pass control when I finish.';else{if(!state.computer.queue.includes(id))state.computer.queue.push(id);reply=`I’ve joined the computer queue at position ${state.computer.queue.indexOf(id)+1}. I’ll wait for the current owner to hand off the lock.`;log(id,'Joined computer queue','Requested exclusive computer access.');}openTab('computer');}
    else if(/brief|document|kickoff/i.test(text)){reply='I’ve brought the Brightside kickoff brief into the workspace. You can edit it, export it, or keep it open alongside the computer.';artifact=true;openTab('document');log(id,'Opened kickoff brief','Artifact is available in the workspace.');}
    else{const t={id:uid(),agent:id,title:text.length>70?text.slice(0,67)+'…':text,description:'Created from your conversation. Demo execution is simulated.',status:'Queued',progress:0};state.tasks.push(t);const autonomous=state.mode==='auto'&&agent(id).autonomy==='auto';reply=autonomous?'I’ve turned that into a task and I’m running the demo now. You’ll see the result in Tasks and Log.':'I’ve prepared a task with that context. Open Tasks and choose “Run demo” when you want me to proceed.';log(id,'Task created from chat',t.title);if(autonomous)setTimeout(()=>runTask(t.id),500);}
    getMessages(id).push({role:'assistant',time:now(),text:reply,artifact});render();if(state.selected===id)$('#conversation-body').scrollTop=$('#conversation-body').scrollHeight;
  },1100);
}
function renderAttachment(){$('#attachment-chip').innerHTML=state.attachment?'<div class="attachment-chip">▤ Meeting notes.txt <span class="muted">Sample attachment</span><button type="button" data-action="remove-attachment" aria-label="Remove attachment">×</button></div>':'';}
function downloadDoc(){const blob=new Blob([`# ${state.document.title}\n## ${state.document.subtitle}\n\n${state.document.body}\n\n---\nSample data from the Sapi prototype.\n`],{type:'text/markdown'});const url=URL.createObjectURL(blob);const a=document.createElement('a');a.href=url;a.download='brightside-kickoff-brief.md';a.click();setTimeout(()=>URL.revokeObjectURL(url),1500);toast('Kickoff brief exported as Markdown.');}
const actions={
  'agent-settings':agentSettings,'new-tab':addTabDialog,'new-task':newTask,'new-schedule':()=>scheduleDialog(),
  'open-brief':()=>openTab('document'),'open-artifacts':()=>openTab('artifacts'),'open-report':()=>openTab('overview'),
  'take-control':()=>{const c=state.computer;if(c.owner==='you'){c.lastUsed='you';c.owner=null;if(!handoff()){render();toast('Computer released. It is available to the team.');}}else{const old=c.owner;c.lastUsed=old||c.lastUsed;if(old&&!c.queue.includes(old))c.queue.unshift(old);if(old)log(old,'You took computer control','Agent input paused; returned to the front of the queue.');c.owner='you';c.paused=false;render();toast('You hold the lock. Agent input is blocked.');}},
  'pause-computer':()=>{if(state.mode==='paused'){toast('Resume the team from the autonomy menu first.');return;}state.computer.paused=!state.computer.paused;log(state.computer.owner&&state.computer.owner!=='you'?state.computer.owner:state.selected,state.computer.paused?'Computer paused':'Computer resumed','Exclusive lock retained by the current controller.');render();toast(state.computer.paused?'Computer paused. The lock is retained.':'Computer session resumed.');},
  'handoff':()=>{if(state.mode==='paused'){toast('Resume the team before handing control to an agent.');return;}handoff();},'join-queue':joinQueue,
  'remove-attachment':()=>{state.attachment=false;renderAttachment();save();},
  'download-document':downloadDoc,
  'edit-document':()=>modal('Edit document',`<form id="document-form" class="form-stack"><label>Document title<input name="title" value="${esc(state.document.title)}" required maxlength="100"></label><label>Subtitle<input name="subtitle" value="${esc(state.document.subtitle)}" required maxlength="100"></label><label>Content<textarea name="body" style="min-height:290px" required>${esc(state.document.body)}</textarea></label><button type="submit" class="button primary">Save document</button></form>`)
};
document.addEventListener('click',e=>{
  const b=e.target.closest('button');if(!b)return;const d=b.dataset;
  if(d.togglePane){state.panes[d.togglePane]=!state.panes[d.togglePane];renderPanes();save();return;}
  if(d.action){actions[d.action]?.();return;}
  if(d.mention){openChat(d.mention);return;}
  if(d.agent){openChat(d.agent);return;}
  if(d.scope){state.scope=d.scope;renderSidebar();save();return;}
  if(d.panel){state.panel=d.panel;renderConversation();save();return;}
  if(d.tab){state.activeTab=d.tab;renderTabs();renderWorkspace();save();return;}
  if(d.closeTab){const i=state.tabs.findIndex(t=>t.id===d.closeTab);if(i<0)return;state.tabs.splice(i,1);if(state.activeTab===d.closeTab)state.activeTab=state.tabs[Math.max(0,i-1)]?.id||null;closeModal();renderTabs();renderWorkspace();save();return;}
  if(d.newTabType){openTab(d.newTabType);closeModal();return;}
  if(d.editTab){tabSettings(d.editTab);return;}
  if(d.moveTab){const i=state.tabs.findIndex(t=>t.id===d.id),j=i+(d.moveTab==='left'?-1:1);if(j<0||j>=state.tabs.length){toast('That tab is already at the edge.');return;}[state.tabs[i],state.tabs[j]]=[state.tabs[j],state.tabs[i]];renderTabs();save();return;}
  if(d.suggest){sendChat(d.suggest);return;}
  if(d.mode){state.mode=d.mode;log(state.selected,'Team autonomy updated',`Workspace mode: ${d.mode}.`);closeModal();render();toast(d.mode==='paused'?'Team paused. Your work is saved.':`Team set to ${d.mode==='auto'?'autonomous':'assisted'}.`);return;}
  if(d.task){taskDetails(d.task);return;}
  if(d.runTask){runTask(d.runTask);return;}
  if(d.taskStatus){const t=state.tasks.find(t=>t.id===d.id);if(pending.has(t.agent)){toast('Wait for the current task execution to finish.');return;}t.status=d.taskStatus;t.progress=t.status==='Done'?100:0;log(t.agent,'Task updated',`${t.title}: ${t.status}`);closeModal();render();return;}
  if(d.toggleSchedule){const s=state.schedules.find(s=>s.id===d.toggleSchedule);s.enabled=!s.enabled;renderConversation();save();return;}
  if(d.editSchedule){scheduleDialog(d.editSchedule);return;}
  if(d.deleteSchedule){state.schedules=state.schedules.filter(s=>s.id!==d.deleteSchedule);closeModal();renderConversation();save();toast('Schedule removed.');return;}
  if(d.runSchedule){const s=state.schedules.find(s=>s.id===d.runSchedule);if(!canRun(s.agent))return;s.runs++;const t={id:uid(),agent:s.agent,title:s.title,description:s.prompt,status:'Queued',progress:0};state.tasks.push(t);log(s.agent,'Schedule triggered manually',s.frequency);runTask(t.id);return;}
  if(d.queueAgent){state.computer.queue.push(d.queueAgent);log(d.queueAgent,'Joined computer queue',`Position ${state.computer.queue.length}.`);closeModal();if(!state.computer.owner&&state.mode==='auto'&&!state.computer.paused)handoff(true);else render();toast(`${agent(d.queueAgent).name} added to the computer queue.`);return;}
  if(d.removeQueue){state.computer.queue=state.computer.queue.filter(id=>id!==d.removeQueue);log(d.removeQueue,'Left computer queue','Removed from the waiting list.');render();return;}
  if(d.connection){state.connections[d.connection]=!state.connections[d.connection];renderWorkspace();renderGlobal();save();toast(`${d.connection} ${state.connections[d.connection]?'connected':'disconnected'} in the demo.`);return;}
  if(d.pr){modal(`Pull request #${d.pr}`,`<p>${d.pr==='142'?'Adds single sign-on for Brightside pilot accounts. The authentication checks pass in this sample repository.':'This sample pull request has been merged into the main branch.'}</p><div class="execution-card"><div class="execution-title">✓ Checks complete <span>3 / 3</span></div><div class="execution-line">✓ Type checks passed</div><div class="execution-line">✓ Authentication tests passed</div><div class="execution-line">✓ Preview build ready</div></div><p class="form-hint">Static sample results for the clickable prototype.</p><div class="modal-actions"><button class="button primary" data-action="review-pr">Ask Aaron to review</button></div>`);return;}
});
actions['review-pr']=()=>{closeModal();state.selected='aaron';state.panel='chat';render();sendChat('Review the SSO pull request and summarize the changes');};
document.addEventListener('submit',e=>{const f=e.target;if(f.id==='chat-form'){e.preventDefault();sendChat($('#message-input').value);return;}if(!['custom-tab-form','tab-settings-form','agent-settings-form','add-agent-form','new-task-form','schedule-form','document-form','slack-form'].includes(f.id))return;e.preventDefault();const data=Object.fromEntries(new FormData(f));
  if(f.id==='custom-tab-form'){const url=safeUrl(data.url);if(!url){toast('Use a complete http:// or https:// website address.');return;}openTab('custom',data.title,{url});}
  if(f.id==='tab-settings-form'){const t=state.tabs.find(t=>t.id===f.dataset.id);if(t.type==='custom'&&!safeUrl(data.url)){toast('Use an http:// or https:// website address.');return;}t.title=data.title.trim()||tabTypes[t.type][1];if(t.type==='custom')t.url=safeUrl(data.url);}
  if(f.id==='agent-settings-form'){Object.assign(selected(),{name:data.name.trim(),role:data.role.trim(),autonomy:data.autonomy});}
  if(f.id==='add-agent-form'){if(!data.name.trim()||!data.role.trim()){toast('Give your Sapi a name and a role.');return;}const a={...data,id:uid(),name:data.name.trim(),role:data.role.trim(),scope:data.kind==='group'?'team':'personal',status:'online',autonomy:'auto',preview:'Ready for tasks.'};state.agents.push(a);state.selected=a.id;state.scope='all';state.panel='chat';log(a.id,'Joined the workspace','Autonomous mode enabled.');toast(`${a.name} is part of the team.`);}
  if(f.id==='new-task-form'){if(!data.title.trim()){toast('Add a task title.');return;}const t={...data,id:uid(),status:'Queued',progress:0};state.tasks.push(t);log(t.agent,'Task assigned',t.title);state.selected=t.agent;state.panel='tasks';if(state.mode==='auto'&&agent(t.agent).autonomy==='auto'){setTimeout(()=>runTask(t.id),400);}else toast('Task added to the queue.');}
  if(f.id==='schedule-form'){const s=state.schedules.find(s=>s.id===f.dataset.id);if(s)Object.assign(s,data);else state.schedules.push({...data,id:uid(),agent:state.selected,enabled:true,runs:0});log(state.selected,s?'Schedule updated':'Schedule created',data.title);toast('Demo schedule saved. Try it with Run now.');}
  if(f.id==='document-form'){state.document={...data,edited:true};log('aaron','Kickoff brief edited','Your local changes have been saved.');toast('Document saved.');}
  if(f.id==='slack-form'){if(!state.connections.Slack){toast('Reconnect the demo Slack connection to post.');return;}if(!data.post.trim())return;state.posts.push({author:'Alex Parker',time:now(),text:data.post.trim()});log(state.selected,'Demo channel updated','You posted to #brightside-shared.');toast('Posted to the demo channel.');}
  closeModal();render();
});
$('#close-modal').addEventListener('click',closeModal);
$('#modal').addEventListener('click',e=>{if(e.target===$('#modal')){const r=$('#modal').getBoundingClientRect();if(e.clientX<r.left||e.clientX>r.right||e.clientY<r.top||e.clientY>r.bottom)closeModal();}});
$('#add-tab').addEventListener('click',addTabDialog);
$('#add-agent').addEventListener('click',addAgent);
$('#autonomy-button').addEventListener('click',autonomyDialog);
$('#resource-button').addEventListener('click',()=>openTab('computer'));

$('#agent-search').addEventListener('input',e=>{search=e.target.value;renderSidebar();});
$('#attach-button').addEventListener('click',()=>{state.attachment=true;renderAttachment();save();toast('Sample meeting notes attached.');});
$('#message-input').addEventListener('keydown',e=>{if(e.key==='Enter'&&!e.shiftKey&&!e.isComposing){e.preventDefault();sendChat(e.target.value);}});
$('.wordmark').addEventListener('click',e=>{e.preventDefault();openTab('overview');});
$('#workspace-menu').addEventListener('click',()=>{if(state.activeTab)tabSettings(state.activeTab);else addTabDialog();});
$('#profile-button').addEventListener('click',()=>modal('Workspace settings',`<p>Alex Parker’s workspace. A local playground for your autonomous Sapi team.</p><div class="settings-row"><label>Workspace data<p>Agents, tabs, tasks, and edits save in this browser.</p></label><span class="tag">LOCAL</span></div><div class="settings-row"><label>Prototype version<p>01 · Shared computer & autonomous team</p></label></div><div class="modal-actions"><button class="button danger" id="reset-demo">Reset demo data</button><button class="button primary" data-action="close-settings">Done</button></div>`));
actions['close-settings']=closeModal;
document.addEventListener('click',e=>{if(e.target.id==='reset-demo'){if(pending.size){toast('Wait for active demo tasks to finish before resetting.');return;}state=structuredClone(seed);search='';$('#agent-search').value='';closeModal();render();toast('Fresh start. Demo data restored.');}});
document.addEventListener('keydown',e=>{if(e.key==='/'&&!['INPUT','TEXTAREA','SELECT'].includes(document.activeElement.tagName)&&!$('#modal').open){e.preventDefault();state.panes.sidebar=true;renderPanes();save();$('#agent-search').focus();}});
render();
